log:
    level: info
#    file: moneta.log
#    config: misc/logging.conf
plugins:
    path: plugins
    load:
        - mailer
        - audit
        - configbackup
        - executionsummary
    config:
        configbackup:
            path: config-backup.yaml
            format: yaml
pools:
    - default
listen: 127.0.0.1:32000
zookeeper:
    - 127.0.0.1:2181
nodename: mynode
leader: true
