plugins:
    path: plugins
    load:
        - mailer
        - elasticsearch
        - configbackup
    config:
        configbackup:
            path: config-backup.yaml
            format: yaml
pools:
    - default
listen: 127.0.0.1:32000
zookeeper:
    - 127.0.0.1:2181
nodename: mynode